ARG FROM=daetsiinf-printing-web_base
FROM ${FROM} as builder

# Set app workdir
ARG APP_CONTAINER_PATH=/app
WORKDIR ${APP_CONTAINER_PATH}

# # Run tests
# RUN ng test --watch=false

# Build the app
RUN ng build --prod



# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.13.7-alpine

ARG APP_CONTAINER_PATH=/app

COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder
COPY --from=builder ${APP_CONTAINER_PATH}/dist /usr/share/nginx/html

# Run nginx
CMD ["nginx", "-g", "daemon off;"]

